name : drventisette.github.io
brand : drventisette
description : Portfolio
keyword : 
url : http://drventisette.github.io/#
email : drventisette@gmail.com
twitter : drventisette
github : drventisette
author : drventisette
analytics : UA-8418273-8
year : 2015
timezone: Europe/Paris
markdown : kramdown
permalink: pretty
exclude : [node_modules]

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      categories: "posts"
      
